import type { Metadata } from "next"
import "../globals.css"
import Footer from "@/component/ui/footer/footer"
import Header_page from "@/component/ui/header_page/Header_page"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header_page />
      <main style={{paddingTop:"110px"}}>
        {children}
        <Footer />
      </main>
    </>
  )
}
